require("dotenv").config();
const express=require("express"),cors=require("cors"),path=require("path");
const app=express();app.use(cors());app.use(express.json());app.use(express.static(path.join(__dirname,"public")));
const PORT=process.env.PORT||3000,TOKEN=process.env.DUFFEL_ACCESS_TOKEN;
const h={"Authorization":`Bearer ${TOKEN}`,"Duffel-Version":"v2","Content-Type":"application/json","Accept":"application/json"};
app.get("/",(q,s)=>s.sendFile(path.join(__dirname,"public","index.html")));
app.get("/health",(q,s)=>s.json({status:"ok",duffelConfigured:Boolean(TOKEN)}));
app.post("/api/flights/search",async(q,s)=>{try{if(!TOKEN)return s.status(500).json({error:"DUFFEL_ACCESS_TOKEN is not configured."});let{origin,destination,departureDate,returnDate,adults=1,cabinClass="economy"}=q.body;if(!origin||!destination||!departureDate)return s.status(400).json({error:"Origin, destination and departure date are required."});let o=origin.trim().toUpperCase(),d=destination.trim().toUpperCase(),slices=[{origin:o,destination:d,departure_date:departureDate}];if(returnDate)slices.push({origin:d,destination:o,departure_date:returnDate});let r=await fetch("https://api.duffel.com/air/offer_requests?return_offers=true&view=offers",{method:"POST",headers:h,body:JSON.stringify({data:{slices,passengers:Array.from({length:Math.max(1,+adults||1)},()=>({type:"adult"})),cabin_class:cabinClass,max_connections:2}})}),j=await r.json();if(!r.ok)return s.status(r.status).json({error:"Duffel offer request failed",details:j});let offers=j.data?.offers||[];if(!offers.length&&j.data?.id){let g=await fetch(`https://api.duffel.com/air/offer_requests/${j.data.id}?view=offers`,{headers:h}),x=await g.json();if(!g.ok)return s.status(g.status).json({error:"Duffel offer retrieval failed",details:x});offers=x.data?.offers||[]}offers.sort((a,b)=>(+a.total_amount||Infinity)-(+b.total_amount||Infinity));s.json({offerRequestId:j.data?.id||null,count:offers.length,offers})}catch(e){s.status(500).json({error:"Flight search failed",details:e.message})}});
app.listen(PORT,()=>console.log(`CheapTrip backend v3 running on port ${PORT}`));
